# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
import std/[os, strutils, algorithm]
import db_connector/db_sqlite
import nimib, nimibook
import UniMedia/[types, store]

nbInit(theme = useNimibook)

nbText: """
# The database

One SQLite file at the library root, `.organizeMedia.db`. Everything UniMedia
knows lives there and nowhere else — no index elsewhere on the machine, no
cache that has to agree with it.

This page is generated by opening a real library, so it cannot drift from the
schema the code actually creates.
"""

# A throwaway library, so the schema below is the one this version writes.
let root = getTempDir() / ("unimedia-book-schema-" & $getCurrentProcessId())
removeDir(root)
createDir(root)
discard initLibrary(root, mdVisual)
var catalogue = openLibrary(root)

nbText: "The version this build creates:"
nbCode:
  echo "schema version ", CurrentSchema

nbText: """
## The tables

`items` is the centre; everything else refers to it. Two groups are worth
telling apart: what UniMedia **read** from your files, and what **you** told it.
A rescan may replace the first and must never touch the second.
"""

block:
  var names: seq[string]
  for row in catalogue.db.getAllRows(sql"""
      SELECT name FROM sqlite_master WHERE type='table'
      AND name NOT LIKE 'sqlite_%'"""):
    names.add row[0]
  names.sort()
  var rows: string
  for name in names:
    let count = catalogue.db.getAllRows(sql("PRAGMA table_info(" & name & ")")).len
    rows.add "| `" & name & "` | " & $count & " |\n"
  nbText: "| Table | Columns |\n|---|---|\n" & rows

nbText: """
### items

One row per file. `rel_path` is relative to the library root, which is what
lets a library move to another disk without losing its catalogue.

`date_source` says where the capture date came from, and it is the field to
look at when a date surprises you:

- `metadata` — read from the file itself. Trustworthy unless the camera's clock
  was wrong.
- `filename` — read from a name like `20090329_011303.jpg`. Right when the
  camera named the file, wrong when something re-encoded it.
- empty — no date was found. The file is filed as undated rather than given a
  date that would be a guess.
"""

block:
  var rows: string
  for row in catalogue.db.getAllRows(sql"PRAGMA table_info(items)"):
    rows.add "| `" & row[1] & "` | " & row[2] & " |\n"
  nbText: "| Column | Type |\n|---|---|\n" & rows

nbText: """
### batches and batch_ops

The journal. A batch is one operation; a `batch_ops` row is one file within it,
written **before** the file is touched and carrying the digest of what was
there. That ordering is the whole recovery story: an interrupted run leaves a
journal describing what it meant to do, so the next one can finish or reverse
it.
"""

block:
  var rows: string
  for row in catalogue.db.getAllRows(sql"PRAGMA table_info(batch_ops)"):
    rows.add "| `" & row[1] & "` | " & row[2] & " |\n"
  nbText: "| Column | Type |\n|---|---|\n" & rows

nbText: """
A batch's `status` is how far it got, and whether there is a way back:

| Status | Meaning |
|---|---|
| `pending` | Journalled, nothing done yet |
| `applying` | In progress; an interrupted run is reconciled from here |
| `applied` | Done, and undoable |
| `partial` | Some operations failed; what succeeded is still undoable |
| `undone` | Reversed |
| `emptied` | Its trash was deleted — `undo` refuses this one by name |

### item_curations

What **you** said, as opposed to what the file said: title, keywords, rating,
creator, copyright, a corrected date, a corrected position. Kept apart from
`items` for one reason — a rescan rewrites what was read and must never
overwrite what was entered. The same values are mirrored into an XMP sidecar,
so they travel with the picture to any other program.
"""

catalogue.close()
removeDir(root)

nbSave
